# We have a conf and classes directory, add to BBPATH
BBPATH =. "${LAYERDIR}:"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "mantle-distro-layer"
BBFILE_PATTERN_mantle-distro-layer = "^${LAYERDIR}/"
BBFILE_PRIORITY_mantle-distro-layer = "20"

## FIXME this distro depends on so much more
#    qt5-layer
LAYERDEPENDS_mantle-distro-layer = " \
    core yocto yoctobsp \
    \
    openembedded-layer \
    filesystems-layer \
    networking-layer \
    perl-layer \
    meta-python \
    multimedia-layer \
    meta-initramfs \
    xfce-layer \
    gnome-layer \
    webserver \
    \
    qt6-layer \
    kf6-layer \
    \
    iot-cloud \
    virtualization-layer \
    scarthgap-rust-mixin \
    meta-python2 \
    meta-noto \
    mantle-bsp \
    meta-mantle-java \
    mantle-office-layer \
    flutter-layer \
    erlang-layer \
    clang-layer \
    chromium-browser-layer \
"

LAYERSERIES_COMPAT_mantle-distro-layer = "scarthgap"
LICENSE_PATH:append = " ${LAYERDIR}/licenses "

# poky
BBFILES_DYNAMIC += " \
    core:${LAYERDIR}/dynamic-layers/poky/meta/recipes-*/*/*.bb \
    core:${LAYERDIR}/dynamic-layers/poky/meta/recipes-*/*/*.bbappend \
"

# OE
BBFILES_DYNAMIC += " \
    openembedded-layer:${LAYERDIR}/dynamic-layers/meta-openembedded/openembedded-layer/recipes-*/*/*.bb \
    openembedded-layer:${LAYERDIR}/dynamic-layers/meta-openembedded/openembedded-layer/recipes-*/*/*.bbappend \
    xfce-layer:${LAYERDIR}/dynamic-layers/meta-openembedded/xfce-layer/recipes-*/*/*.bb \
    xfce-layer:${LAYERDIR}/dynamic-layers/meta-openembedded/xfce-layer/recipes-*/*/*.bbappend \
    gnome-layer:${LAYERDIR}/dynamic-layers/meta-openembedded/gnome-layer/recipes-*/*/*.bb \
    gnome-layer:${LAYERDIR}/dynamic-layers/meta-openembedded/gnome-layer/recipes-*/*/*.bbappend \
    webserver:${LAYERDIR}/dynamic-layers/meta-openembedded/webserver-layer/recipes-*/*/*.bb \
    webserver:${LAYERDIR}/dynamic-layers/meta-openembedded/webserver-layer/recipes-*/*/*.bbappend \
    perl-layer:${LAYERDIR}/dynamic-layers/meta-openembedded/perl-layer/recipes-*/*/*.bb \
    perl-layer:${LAYERDIR}/dynamic-layers/meta-openembedded/perl-layer/recipes-*/*/*.bbappend \
    multimedia-layer:${LAYERDIR}/dynamic-layers/meta-openembedded/multimedia-layer/recipes-*/*/*.bb \
    multimedia-layer:${LAYERDIR}/dynamic-layers/meta-openembedded/multimedia-layer/recipes-*/*/*.bbappend \
"

## tier 2
BBFILES_DYNAMIC += " \
    qt5-layer:${LAYERDIR}/dynamic-layers/qt5-layer/recipes-*/*/*.bb \
    qt5-layer:${LAYERDIR}/dynamic-layers/qt5-layer/recipes-*/*/*.bbappend \
    qt6-layer:${LAYERDIR}/dynamic-layers/qt6-layer/recipes-*/*/*.bb \
    qt6-layer:${LAYERDIR}/dynamic-layers/qt6-layer/recipes-*/*/*.bbappend \
    chromium-browser-layer:${LAYERDIR}/dynamic-layers/chromium-browser-layer/recipes-*/*/*.bb \
    chromium-browser-layer:${LAYERDIR}/dynamic-layers/chromium-browser-layer/recipes-*/*/*.bbappend \
    flutter-layer:${LAYERDIR}/dynamic-layers/flutter-layer/recipes-*/*/*.bb \
    flutter-layer:${LAYERDIR}/dynamic-layers/flutter-layer/recipes-*/*/*.bbappend \
"
# broken atm
#   neuralnetwork:${LAYERDIR}/dynamic-layers/ai-layer/recipes-*/*/*.bb 
#    neuralnetwork:${LAYERDIR}/dynamic-layers/ai-layer/recipes-*/*/*.bbappend 
