# We have a conf and classes directory, add to BBPATH
BBPATH =. "${LAYERDIR}:"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "mantle-distro-layer"
BBFILE_PATTERN_mantle-distro-layer = "^${LAYERDIR}/"
BBFILE_PRIORITY_mantle-distro-layer = "20"

## FIXME this distro depends on so much more
LAYERDEPENDS_mantle-distro-layer = " \
    core \
    yocto \
    networking-layer \
    perl-layer \
    meta-python \
"

LAYERSERIES_COMPAT_mantle-distro-layer = "scarthgap"
LICENSE_PATH:append = " ${LAYERDIR}/licenses "

# the dark ages
BBFILES_DYNAMIC += " \
    openembedded-layer:${LAYERDIR}/dynamic-layers/openembedded-layer/recipes-*/*/*.bb \
    openembedded-layer:${LAYERDIR}/dynamic-layers/openembedded-layer/recipes-*/*/*.bbappend \
    xfce-layer:${LAYERDIR}/dynamic-layers/xfce-layer/recipes-*/*/*.bb \
    xfce-layer:${LAYERDIR}/dynamic-layers/xfce-layer/recipes-*/*/*.bbappend \
    gnome-layer:${LAYERDIR}/dynamic-layers/gnome-layer/recipes-*/*/*.bb \
    gnome-layer:${LAYERDIR}/dynamic-layers/gnome-layer/recipes-*/*/*.bbappend \
    webserver:${LAYERDIR}/dynamic-layers/webserver-layer/recipes-*/*/*.bb \
    webserver:${LAYERDIR}/dynamic-layers/webserver-layer/recipes-*/*/*.bbappend \
    perl-layer:${LAYERDIR}/dynamic-layers/perl-layer/recipes-*/*/*.bb \
    perl-layer:${LAYERDIR}/dynamic-layers/perl-layer/recipes-*/*/*.bbappend \
"

## tier 2
BBFILES_DYNAMIC += " \
    qt5-layer:${LAYERDIR}/dynamic-layers/qt5-layer/recipes-*/*/*.bb \
    qt5-layer:${LAYERDIR}/dynamic-layers/qt5-layer/recipes-*/*/*.bbappend \
    qt6-layer:${LAYERDIR}/dynamic-layers/qt6-layer/recipes-*/*/*.bb \
    qt6-layer:${LAYERDIR}/dynamic-layers/qt6-layer/recipes-*/*/*.bbappend \
    chromium-browser-layer:${LAYERDIR}/dynamic-layers/chromium-browser-layer/recipes-*/*/*.bb \
    chromium-browser-layer:${LAYERDIR}/dynamic-layers/chromium-browser-layer/recipes-*/*/*.bbappend \
"
# broken atm
#   neuralnetwork:${LAYERDIR}/dynamic-layers/ai-layer/recipes-*/*/*.bb 
#    neuralnetwork:${LAYERDIR}/dynamic-layers/ai-layer/recipes-*/*/*.bbappend 
