require conf/distro/poky.conf

MANTLE_INIT_TYPE ?= "systemd"
INIT_MANAGER = "${MANTLE_INIT_TYPE}"

MANTLE_POSIX_TYPE   ?= "coreutils"
require conf/distro/include/unix-tools-${MANTLE_POSIX_TYPE}.inc

DISTRO_GRAPHICS_FEATURES ?= " \
    vulkan \
    x11 \
    wayland \
    opengl \
    directfb \
"

MANTLE_FORTRAN ?= "TRUE"
require conf/distro/include/fortan.inc

DISTRO = "mantle"
DISTRO_NAME = "Mantle OS - ${DISTRO_RELEASE}"
DISTRO_CODENAME =  "hadean"
MAINTAINER = "Joseph Mills <josephjamesmills@gmail.com.com>"

RELEASE_DATE = "${@d.getVar('DATE')[:4] + '-' + d.getVar('DATE')[4:6] + '-' + d.getVar('DATE')[6:8]}"
DISTRO_VERSION = "0.0.1"
DISTRO_RELEASE ?= "development"

SDK_VENDOR = "-mantle"
SDK_NAME = "${DISTRO}-${MACHINE}-${TUNE_PKGARCH}-${TCLIBC}-toolchain-${SDK_ARCH}-${SDK_VERSION}"
SDKPATHINSTALL = "/opt/${DISTRO}-${DISTRO_CODENAME}-oe-sdks/${MACHINE}-${TUNE_PKGARCH}-${TCLIBC}-${SDK_VERSION}"

LICENSE_FLAGS_ACCEPTED:append = " \
    commercial \
    commercial_libav \
    commercial_mpg123 \
    commercial_x264 \
    commercial_libpostproc \
    commercial_gst-ffmpeg \
    commercial_gst-plugins-ugly \
    commercial_libmad \
    commercial_mpeg2dec \
    commercial_lame \
"

## oe/poky
DISTRO_FEATURES:remove = "debuginfod ptest"
DISTRO_FEATURES:append = " \
    pam \
    ${@bb.utils.contains_any('BBFILE_COLLECTIONS', 'qt6-layer qt5-layer', ' webengine', '', d)} \
    polkit \
"
# later hurd needs ext2 lol
DISTRO_FEATURES:remove = " \
    ${@bb.utils.contains_any('BBFILE_COLLECTIONS', 'meta-hurd', '', 'ext2', d)} \
"

# meta-virtualization
DISTRO_FEATURES:append =  " virtualization seccomp "

#meta-qt -> webengine building
DISTRO_FEATURES:append = "${@bb.utils.contains_any('BBFILE_COLLECTIONS', 'qt5-layer qt6-layer', ' webengine', '', d)}"

PREFERRED_RPROVIDER_ssh = "openssh"


#required-distro-features.inc  wayland-protocols_1.45.bb  weston_14.0.2.bb
#libinput_1.29.1.bb  wayland                       wayland-utils_1.2.0.bb     weston-init
#mtdev_1.1.7.bb      wayland_1.24.0.bb             weston                     weston-init.bb



